
# Load necessary packages

library('plyr')
library('dplyr')
library('tidyr')
library('sjPlot')

## Read base cases results into the global environment
#setwd("~/results") 
#import files to use
incidenceReport=read.table("incidenceReport.txt", sep="\t", header=TRUE)
                          # Incidence Report (Overall)
iduReport=read.table("iduReport.txt",sep="\t", 
                     header=TRUE) # Injection Drug User Report (Overall)


#list all files and get rid of any that might be generated by this script
temp=list.files(pattern = "Inc*")
Filter(function(x) !any(grepl("_Mean", x)), temp)
Filter(function(x) !any(grepl("_Cum", x)), temp)

for (i in 1:length(temp)){
  assign('temp2' , read.table(temp[i],header = TRUE))
  temp2 <- temp2[order(temp2[,1]),]
  assign(gsub(".txt", "", temp[i]),temp2)
}
  


