# This script reads in the files needed for analysis. It takes all files that
# include "basic" in their names, then excludes any that have been previously
# analyzed with this script. Unless you want to use on other files, the only
# thing you need to change is the directory where your files are found.

# choose directory starting from your home directory
fileDir <- "~/Documents/outPutAnalysis/TITAN/results"

# Load necessary packages

library('plyr')
library('dplyr')
library('tidyr')
library('ggplot2')

## Read base cases results into the global environment
#setwd("~/results") 

#list all files and get rid of any that might be generated by this script
temp=list.files(fileDir, pattern = "*basic*")
temp <- Filter(function(x) !any(grepl("_Mean", x)), temp)
temp <- Filter(function(x) !any(grepl("_Cum", x)), temp)
dataframe_names <- list()
dataframe_names <- gsub(".txt", "", temp)

#should work, needs to be checked with corrected basic reports
for (i in 1:length(temp)){
  assign('temp2' , read.table(paste("results/",temp[i], sep = ""),header = TRUE))
  temp2 <- temp2[order(temp2[,1]),]
  assign(gsub(".txt", "", temp[i]),temp2)
}



