# This script reads in the files needed for analysis. It takes all files that
# include "basic" in their names, then excludes any that have been previously
# analyzed with this script. Unless you want to use on other files, the only
# thing you need to change is the directory where your files are found.

# This file allows you to change file names, colors, etc.

# choose directory starting from your home directory
setwd("~/data/sbessey/Scott/results")

# choose files to run
# if you don't want all reports, simply set them to "F"
black = T
white = T
HF = T
HM = T
MSM = T
Incar = F
writeTable = T # writes output tables with cumulative incidence, mean, SIs

# set some parameters
plotType = ".pdf" # eps won't work for this, but choose a filetype for the saved plot
transparency = .3 # how transparent the ribbon on the plot is
plotColor = 'blue' # color for the ribbon



## Read base cases results into the global environment


# list all files and get rid of any that might be generated by this script
# list all files that include "basic"
temp=list.files(pattern = "*basic*")
# get rid of files that may be created by this script
temp <- Filter(function(x) !any(grepl("_Mean", x)), temp)
temp <- Filter(function(x) !any(grepl("_Cum", x)), temp)
temp <- Filter(function(x) !any(grepl(".pdf", x)), temp)
dataframe_names <- list()
dataframe_names <- gsub(".txt", "", temp)

# import the files from the data frame of names
for (i in 1:length(temp)){
  assign('temp2' , read.table(temp[i],header = TRUE))
  temp2 <- temp2[order(temp2[,1]),]
  assign(gsub(".txt", "", temp[i]),temp2)
}


# run files
if (black == T){
  if (exists("basicReport_BLACK")){
    accumulate(basicReport_BLACK, plotType, plotColor, transparency, writeTable)
  } else{
    print("Error: basicReport_BLACK does not exist")
  }
}
if (white == T){
  if (exists("basicReport_WHITE")){
    accumulate(basicReport_WHITE,plotType, plotColor, transparency, writeTable)
  } else{
    print("Error: basicReport_WHITE does not exist")
  }
}
if (HF == T){
  if (exists("basicReport_HF")){
    accumulate(basicReport_HF, plotType, plotColor, transparency, writeTable)
  } else{
    print("Error: basicReport_HF does not exist")
  }
}
if (HM == T){
  if (exists("basicReport_HM")){
    accumulate(basicReport_HM, plotType, plotColor, transparency, writeTable)
  } else{
    print("Error: basicReport_HM does not exist")
  }
}
if (MSM == T){
  if (exists("basicReport_MSM")){
    accumulate(basicReport_MSM, plotType, plotColor, transparency, writeTable)
  } else{
    print("Error: basicReport_MSM does not exist")
  }
}
if (Incar == T){
  if (exists("basicReport_INCAR")){
    accumulate(basicReport_INCAR, plotType, plotColor, transparency, writeTable)
  } else{
    print("Error: basicReport_INCAR does not exist")
  }
}

